name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Step 0 - Checkout repository
        uses: actions/checkout@v2

      - name: Preparation
        run: |
          pwd
          tree

      - name: Step 1 - Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Step 2 - Build Java Program
        run: |
          # Compile and build your Java program
          javac -d build src/main/java/org/example/*.java
          jar cvf your_program.jar -C build .

      - name: Step 3 - Generate File
        id: generate-file
        run: |
          # Run your Java program and capture the file name
          file_name=$(java -jar your_program.jar)
          echo "::set-output name=file-name::${file_name}"

      - name: Step 4 - Run Script
        run: |
          # Use the file name generated in Step 3
          file_name=${{ steps.generate-file.outputs.file-name }}
          scripts_directory="scripts"  # Specify the directory path if needed
          java -jar script_runner.jar "$scripts_directory/$file_name"
