name: Example Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Build Java Program
        run: |
          # Compile and build your Java program
          pwd
          javac -d build src/main/java/org/example/FileGenerator.java
          pwd
          jar cvf FileGenerator.jar -C build .

      - name: Step 2 - Generate File
        id: generate-file
        run: |
          # Run your Java program and capture the file name
          file_name=$(java -jar FileGenerator.jar)
          echo "::set-output name=file-name::${file_name}"

      - name: Step 3 - Run Script
        run: |
          # Use the file name generated in Step 2
          file_name=${{ steps.generate-file.outputs.file-name }}
          scripts_directory="scripts"  # Specify the directory path if needed
          java -jar script_runner.jar "$scripts_directory/$file_name"
