name: Example Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Step 0 - Checkout repository
        uses: actions/checkout@v2
        with:
          ref: 'master'

      - name: Step 1 - Print Working Directory
        run: |
          # Print the current working directory
          pwd

      - name: Step 2 - List Directory Contents
        run: |
          # Print the directory tree structure
          tree

      - name: Step 3 - Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          
      - name: Step 4 - Build Java Program
        run: |
          # Compile and build your Java program
          javac -d classes src/main/java/org/example/FileGenerator.java
          tree
          echo "Main-Class: org.example.FileGenerator" > manifest.txt
          jar cvfm FileGenerator.jar manifest.txt -C build .
          tree

      - name: Step 5 - Generate File
        id: generate-file
        run: |
          # Run your Java program and capture the file name
          file_name=$(java -jar FileGenerator.jar)
          echo "::set-output name=file-name::${file_name}"

      - name: Step 6 - Run Script
        run: |
          # Use the file name generated in Step 5
          file_name=${{ steps.generate-file.outputs.file-name }}
          scripts_directory="scripts"  # Specify the directory path if needed
          java -jar script_runner.jar "$scripts_directory/$file_name"
