name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Compile and run Java program
        run: |
          # Compile the Java program
          pwd
          javac MyProgram.java
          # Run the Java program to generate files
          java MyProgram

      - name: Get generated file name
        id: get-file-name
        run: |
          # List the contents of the 'scripts' directory and capture the filename(s)
          dir scripts
          echo "::set-output name=generated-files::$(dir /B /A-D scripts)"

      - name: Use generated file in subsequent steps
        run: |
          # Retrieve the generated file names and use them in subsequent steps
          filenames=${{ steps.get-file-name.outputs.generated-files }}
          # Iterate over the filenames or select a specific one based on your criteria
          for %%F in ($filenames) do (
            echo "Using file: %%F"
            # ... other commands that require the file
          )
