name: Java CI with Maven

on:
  push:
    branches: [ "feature" ]
  pull_request:
    branches: [ "feature" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn package
    - name: Execute Git Log
      run: |
        git log -1 --name-status
        git branch
        git log --oneline
        pwd
        ls -la
        ls -la target
        
    - name: Compile and run Java program
      run: |
        pwd
        tree
        echo ${{ github.repository }}
        java -cp target\GitApp-1.0-SNAPSHOT.jar org.example.GitAppMain ${{ github.repository }}
